jobs:
- job: Azure_Pipelines
  displayName: 'Azure_Pipelines'
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: PowerShell@2
    displayName: 'Run Core tests'
    inputs:
      pwsh: true
      targetType: Inline
      script: ./azure-pipelines/build.ps1 -Bootstrap -Test

  - task: PowerShell@2
    displayName: 'Run tests'
    inputs:
      pwsh: false
      targetType: Inline
      script: ./azure-pipelines/build.ps1 -Bootstrap -Test

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      testRunner: NUnit
      testResultsFiles: '**/TestResults.xml'
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@0
    displayName: 'Publish compiled module artifact'
    inputs:
      artifactName: 'PoshBot.Rubrik'
      targetPath: ./PoshBot.Rubrik
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Pipelines scripts as artifact'
    inputs:
      artifactName: 'PipelinesScripts'
      targetPath: ./azure-pipelines
    condition: succeededOrFailed()
